name: Update Steam

on:
  push:
    branches:
      - gh-pages

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Get dist
      run: |
        git clone https://github.com/Pseudo-Corp/SynergismOfficial
        cd SynergismOfficial
        git checkout gh-pages
        ls
